timeline_buttons_enabled:
  default: true
  client: true

mobile_buttons_enabled:
  default: true
  client: true

footer_button_enabled:
  default: true
  client: true

footer_button_label:
  default: "Jump"
  client: true

footer_button_title:
  default: "jump to the top of this topic"
  client: true
  
